/**
 * 小企业财税开放平台API Gateway 后端服务RestApi标准文档说明
 * http://www.17dz.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cn.com.servyou.xqy.openapi.client.sky.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Sheet 资产负债表和资产利润表属性说明
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T13:42:20.693+08:00")
public class Sheet {
    @SerializedName("warn")
    private Boolean warn                    = null;

    @SerializedName("row")
    private Integer row                     = null;

    @SerializedName("number")
    private Integer number                  = null;

    @SerializedName("pRowNum")
    private Integer pRowNum                 = null;

    @SerializedName("showLine")
    private Integer showLine                = null;

    @SerializedName("fomularDetail")
    private String  fomularDetail           = null;

    @SerializedName("limitFomularDetail")
    private String  limitFomularDetail      = null;

    @SerializedName("nonLimitFomularDetail")
    private String  nonLimitFomularDetail   = null;

    @SerializedName("accountTitleName")
    private String  accountTitleName        = null;

    @SerializedName("yearBeginBalance")
    private Double  yearBeginBalance        = null;

    @SerializedName("balanceEnd")
    private Double  balanceEnd              = null;

    @SerializedName("occurredAmount")
    private Double  occurredAmount          = null;

    @SerializedName("yearAccumulated")
    private Double  yearAccumulated         = null;

    @SerializedName("preYearAccumulated")
    private Double  preYearAccumulated      = null;

    @SerializedName("amountOfLocalPeriod")
    private Double  amountOfLocalPeriod     = null;

    @SerializedName("amountOfPrePeriod")
    private Double  amountOfPrePeriod       = null;

    @SerializedName("quarterOne")
    private Double  quarterOne              = null;

    @SerializedName("quarterTwo")
    private Double  quarterTwo              = null;

    @SerializedName("quarterThree")
    private Double  quarterThree            = null;

    @SerializedName("quarterFour")
    private Double  quarterFour             = null;

    @SerializedName("limitOccurreAmount")
    private Double  limitOccurreAmount      = null;

    @SerializedName("nonLimitOccurreAmout")
    private Double  nonLimitOccurreAmout    = null;

    @SerializedName("limitYearAccumulated")
    private Double  limitYearAccumulated    = null;

    @SerializedName("nonLimitYearAccumulated")
    private Double  nonLimitYearAccumulated = null;

    public Sheet warn(Boolean warn) {
        this.warn = warn;
        return this;
    }

    /**
    * 是否是异常数据
    * @return warn
    **/
    @ApiModelProperty(example = "null", value = "是否是异常数据")
    public Boolean getWarn() {
        return warn;
    }

    public void setWarn(Boolean warn) {
        this.warn = warn;
    }

    public Sheet row(Integer row) {
        this.row = row;
        return this;
    }

    /**
    * 行次
    * @return row
    **/
    @ApiModelProperty(example = "null", value = "行次")
    public Integer getRow() {
        return row;
    }

    public void setRow(Integer row) {
        this.row = row;
    }

    public Sheet number(Integer number) {
        this.number = number;
        return this;
    }

    /**
    * 序号
    * @return number
    **/
    @ApiModelProperty(example = "null", value = "序号")
    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Sheet pRowNum(Integer pRowNum) {
        this.pRowNum = pRowNum;
        return this;
    }

    /**
    * 父级序号
    * @return pRowNum
    **/
    @ApiModelProperty(example = "null", value = "父级序号")
    public Integer getPRowNum() {
        return pRowNum;
    }

    public void setPRowNum(Integer pRowNum) {
        this.pRowNum = pRowNum;
    }

    public Sheet showLine(Integer showLine) {
        this.showLine = showLine;
        return this;
    }

    /**
    * 是否显示行号
    * @return showLine
    **/
    @ApiModelProperty(example = "null", value = "是否显示行号")
    public Integer getShowLine() {
        return showLine;
    }

    public void setShowLine(Integer showLine) {
        this.showLine = showLine;
    }

    public Sheet fomularDetail(String fomularDetail) {
        this.fomularDetail = fomularDetail;
        return this;
    }

    /**
    * 公式注释说明
    * @return fomularDetail
    **/
    @ApiModelProperty(example = "null", value = "公式注释说明")
    public String getFomularDetail() {
        return fomularDetail;
    }

    public void setFomularDetail(String fomularDetail) {
        this.fomularDetail = fomularDetail;
    }

    public Sheet limitFomularDetail(String limitFomularDetail) {
        this.limitFomularDetail = limitFomularDetail;
        return this;
    }

    /**
    * 限定性注释说明
    * @return limitFomularDetail
    **/
    @ApiModelProperty(example = "null", value = "限定性注释说明")
    public String getLimitFomularDetail() {
        return limitFomularDetail;
    }

    public void setLimitFomularDetail(String limitFomularDetail) {
        this.limitFomularDetail = limitFomularDetail;
    }

    public Sheet nonLimitFomularDetail(String nonLimitFomularDetail) {
        this.nonLimitFomularDetail = nonLimitFomularDetail;
        return this;
    }

    /**
    * 非限定性注释说明
    * @return nonLimitFomularDetail
    **/
    @ApiModelProperty(example = "null", value = "非限定性注释说明")
    public String getNonLimitFomularDetail() {
        return nonLimitFomularDetail;
    }

    public void setNonLimitFomularDetail(String nonLimitFomularDetail) {
        this.nonLimitFomularDetail = nonLimitFomularDetail;
    }

    public Sheet accountTitleName(String accountTitleName) {
        this.accountTitleName = accountTitleName;
        return this;
    }

    /**
    * 科目名称
    * @return accountTitleName
    **/
    @ApiModelProperty(example = "null", value = "科目名称")
    public String getAccountTitleName() {
        return accountTitleName;
    }

    public void setAccountTitleName(String accountTitleName) {
        this.accountTitleName = accountTitleName;
    }

    public Sheet yearBeginBalance(Double yearBeginBalance) {
        this.yearBeginBalance = yearBeginBalance;
        return this;
    }

    /**
    * 年初余额
    * @return yearBeginBalance
    **/
    @ApiModelProperty(example = "null", value = "年初余额")
    public Double getYearBeginBalance() {
        return yearBeginBalance;
    }

    public void setYearBeginBalance(Double yearBeginBalance) {
        this.yearBeginBalance = yearBeginBalance;
    }

    public Sheet balanceEnd(Double balanceEnd) {
        this.balanceEnd = balanceEnd;
        return this;
    }

    /**
    * 期末余额
    * @return balanceEnd
    **/
    @ApiModelProperty(example = "null", value = "期末余额")
    public Double getBalanceEnd() {
        return balanceEnd;
    }

    public void setBalanceEnd(Double balanceEnd) {
        this.balanceEnd = balanceEnd;
    }

    public Sheet occurredAmount(Double occurredAmount) {
        this.occurredAmount = occurredAmount;
        return this;
    }

    /**
    * 本月发生额
    * @return occurredAmount
    **/
    @ApiModelProperty(example = "null", value = "本月发生额")
    public Double getOccurredAmount() {
        return occurredAmount;
    }

    public void setOccurredAmount(Double occurredAmount) {
        this.occurredAmount = occurredAmount;
    }

    public Sheet yearAccumulated(Double yearAccumulated) {
        this.yearAccumulated = yearAccumulated;
        return this;
    }

    /**
    * 本年累计发生额
    * @return yearAccumulated
    **/
    @ApiModelProperty(example = "null", value = "本年累计发生额")
    public Double getYearAccumulated() {
        return yearAccumulated;
    }

    public void setYearAccumulated(Double yearAccumulated) {
        this.yearAccumulated = yearAccumulated;
    }

    public Sheet preYearAccumulated(Double preYearAccumulated) {
        this.preYearAccumulated = preYearAccumulated;
        return this;
    }

    /**
    * 上一年累计发生额
    * @return preYearAccumulated
    **/
    @ApiModelProperty(example = "null", value = "上一年累计发生额")
    public Double getPreYearAccumulated() {
        return preYearAccumulated;
    }

    public void setPreYearAccumulated(Double preYearAccumulated) {
        this.preYearAccumulated = preYearAccumulated;
    }

    public Sheet amountOfLocalPeriod(Double amountOfLocalPeriod) {
        this.amountOfLocalPeriod = amountOfLocalPeriod;
        return this;
    }

    /**
    * 本期发生额
    * @return amountOfLocalPeriod
    **/
    @ApiModelProperty(example = "null", value = "本期发生额")
    public Double getAmountOfLocalPeriod() {
        return amountOfLocalPeriod;
    }

    public void setAmountOfLocalPeriod(Double amountOfLocalPeriod) {
        this.amountOfLocalPeriod = amountOfLocalPeriod;
    }

    public Sheet amountOfPrePeriod(Double amountOfPrePeriod) {
        this.amountOfPrePeriod = amountOfPrePeriod;
        return this;
    }

    /**
    * 上期发生额
    * @return amountOfPrePeriod
    **/
    @ApiModelProperty(example = "null", value = "上期发生额")
    public Double getAmountOfPrePeriod() {
        return amountOfPrePeriod;
    }

    public void setAmountOfPrePeriod(Double amountOfPrePeriod) {
        this.amountOfPrePeriod = amountOfPrePeriod;
    }

    public Sheet quarterOne(Double quarterOne) {
        this.quarterOne = quarterOne;
        return this;
    }

    /**
    * 月-季报-第一季度发生额
    * @return quarterOne
    **/
    @ApiModelProperty(example = "null", value = "月-季报-第一季度发生额")
    public Double getQuarterOne() {
        return quarterOne;
    }

    public void setQuarterOne(Double quarterOne) {
        this.quarterOne = quarterOne;
    }

    public Sheet quarterTwo(Double quarterTwo) {
        this.quarterTwo = quarterTwo;
        return this;
    }

    /**
    * 月-季报-第二季度发生额
    * @return quarterTwo
    **/
    @ApiModelProperty(example = "null", value = "月-季报-第二季度发生额")
    public Double getQuarterTwo() {
        return quarterTwo;
    }

    public void setQuarterTwo(Double quarterTwo) {
        this.quarterTwo = quarterTwo;
    }

    public Sheet quarterThree(Double quarterThree) {
        this.quarterThree = quarterThree;
        return this;
    }

    /**
    * 月-季报-第三季度发生额
    * @return quarterThree
    **/
    @ApiModelProperty(example = "null", value = "月-季报-第三季度发生额")
    public Double getQuarterThree() {
        return quarterThree;
    }

    public void setQuarterThree(Double quarterThree) {
        this.quarterThree = quarterThree;
    }

    public Sheet quarterFour(Double quarterFour) {
        this.quarterFour = quarterFour;
        return this;
    }

    /**
    * 月-季报-第四季度发生额
    * @return quarterFour
    **/
    @ApiModelProperty(example = "null", value = "月-季报-第四季度发生额")
    public Double getQuarterFour() {
        return quarterFour;
    }

    public void setQuarterFour(Double quarterFour) {
        this.quarterFour = quarterFour;
    }

    public Sheet limitOccurreAmount(Double limitOccurreAmount) {
        this.limitOccurreAmount = limitOccurreAmount;
        return this;
    }

    /**
    * 限定性本月发生额
    * @return limitOccurreAmount
    **/
    @ApiModelProperty(example = "null", value = "限定性本月发生额")
    public Double getLimitOccurreAmount() {
        return limitOccurreAmount;
    }

    public void setLimitOccurreAmount(Double limitOccurreAmount) {
        this.limitOccurreAmount = limitOccurreAmount;
    }

    public Sheet nonLimitOccurreAmout(Double nonLimitOccurreAmout) {
        this.nonLimitOccurreAmout = nonLimitOccurreAmout;
        return this;
    }

    /**
    * 非限定性本月发生额
    * @return nonLimitOccurreAmout
    **/
    @ApiModelProperty(example = "null", value = "非限定性本月发生额")
    public Double getNonLimitOccurreAmout() {
        return nonLimitOccurreAmout;
    }

    public void setNonLimitOccurreAmout(Double nonLimitOccurreAmout) {
        this.nonLimitOccurreAmout = nonLimitOccurreAmout;
    }

    public Sheet limitYearAccumulated(Double limitYearAccumulated) {
        this.limitYearAccumulated = limitYearAccumulated;
        return this;
    }

    /**
    * 限定性本年累计发生额
    * @return limitYearAccumulated
    **/
    @ApiModelProperty(example = "null", value = "限定性本年累计发生额")
    public Double getLimitYearAccumulated() {
        return limitYearAccumulated;
    }

    public void setLimitYearAccumulated(Double limitYearAccumulated) {
        this.limitYearAccumulated = limitYearAccumulated;
    }

    public Sheet nonLimitYearAccumulated(Double nonLimitYearAccumulated) {
        this.nonLimitYearAccumulated = nonLimitYearAccumulated;
        return this;
    }

    /**
    * 非限定性本年累计发生额
    * @return nonLimitYearAccumulated
    **/
    @ApiModelProperty(example = "null", value = "非限定性本年累计发生额")
    public Double getNonLimitYearAccumulated() {
        return nonLimitYearAccumulated;
    }

    public void setNonLimitYearAccumulated(Double nonLimitYearAccumulated) {
        this.nonLimitYearAccumulated = nonLimitYearAccumulated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Sheet sheet = (Sheet) o;
        return Objects.equals(this.warn, sheet.warn) && Objects.equals(this.row, sheet.row)
               && Objects.equals(this.number, sheet.number)
               && Objects.equals(this.pRowNum, sheet.pRowNum)
               && Objects.equals(this.showLine, sheet.showLine)
               && Objects.equals(this.fomularDetail, sheet.fomularDetail)
               && Objects.equals(this.limitFomularDetail, sheet.limitFomularDetail)
               && Objects.equals(this.nonLimitFomularDetail, sheet.nonLimitFomularDetail)
               && Objects.equals(this.accountTitleName, sheet.accountTitleName)
               && Objects.equals(this.yearBeginBalance, sheet.yearBeginBalance)
               && Objects.equals(this.balanceEnd, sheet.balanceEnd)
               && Objects.equals(this.occurredAmount, sheet.occurredAmount)
               && Objects.equals(this.yearAccumulated, sheet.yearAccumulated)
               && Objects.equals(this.preYearAccumulated, sheet.preYearAccumulated)
               && Objects.equals(this.amountOfLocalPeriod, sheet.amountOfLocalPeriod)
               && Objects.equals(this.amountOfPrePeriod, sheet.amountOfPrePeriod)
               && Objects.equals(this.quarterOne, sheet.quarterOne)
               && Objects.equals(this.quarterTwo, sheet.quarterTwo)
               && Objects.equals(this.quarterThree, sheet.quarterThree)
               && Objects.equals(this.quarterFour, sheet.quarterFour)
               && Objects.equals(this.limitOccurreAmount, sheet.limitOccurreAmount)
               && Objects.equals(this.nonLimitOccurreAmout, sheet.nonLimitOccurreAmout)
               && Objects.equals(this.limitYearAccumulated, sheet.limitYearAccumulated)
               && Objects.equals(this.nonLimitYearAccumulated, sheet.nonLimitYearAccumulated);
    }

    @Override
    public int hashCode() {
        return Objects.hash(warn, row, number, pRowNum, showLine, fomularDetail, limitFomularDetail,
            nonLimitFomularDetail, accountTitleName, yearBeginBalance, balanceEnd, occurredAmount,
            yearAccumulated, preYearAccumulated, amountOfLocalPeriod, amountOfPrePeriod, quarterOne,
            quarterTwo, quarterThree, quarterFour, limitOccurreAmount, nonLimitOccurreAmout,
            limitYearAccumulated, nonLimitYearAccumulated);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Sheet {\n");

        sb.append("    warn: ").append(toIndentedString(warn)).append("\n");
        sb.append("    row: ").append(toIndentedString(row)).append("\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    pRowNum: ").append(toIndentedString(pRowNum)).append("\n");
        sb.append("    showLine: ").append(toIndentedString(showLine)).append("\n");
        sb.append("    fomularDetail: ").append(toIndentedString(fomularDetail)).append("\n");
        sb.append("    limitFomularDetail: ").append(toIndentedString(limitFomularDetail))
            .append("\n");
        sb.append("    nonLimitFomularDetail: ").append(toIndentedString(nonLimitFomularDetail))
            .append("\n");
        sb.append("    accountTitleName: ").append(toIndentedString(accountTitleName)).append("\n");
        sb.append("    yearBeginBalance: ").append(toIndentedString(yearBeginBalance)).append("\n");
        sb.append("    balanceEnd: ").append(toIndentedString(balanceEnd)).append("\n");
        sb.append("    occurredAmount: ").append(toIndentedString(occurredAmount)).append("\n");
        sb.append("    yearAccumulated: ").append(toIndentedString(yearAccumulated)).append("\n");
        sb.append("    preYearAccumulated: ").append(toIndentedString(preYearAccumulated))
            .append("\n");
        sb.append("    amountOfLocalPeriod: ").append(toIndentedString(amountOfLocalPeriod))
            .append("\n");
        sb.append("    amountOfPrePeriod: ").append(toIndentedString(amountOfPrePeriod))
            .append("\n");
        sb.append("    quarterOne: ").append(toIndentedString(quarterOne)).append("\n");
        sb.append("    quarterTwo: ").append(toIndentedString(quarterTwo)).append("\n");
        sb.append("    quarterThree: ").append(toIndentedString(quarterThree)).append("\n");
        sb.append("    quarterFour: ").append(toIndentedString(quarterFour)).append("\n");
        sb.append("    limitOccurreAmount: ").append(toIndentedString(limitOccurreAmount))
            .append("\n");
        sb.append("    nonLimitOccurreAmout: ").append(toIndentedString(nonLimitOccurreAmout))
            .append("\n");
        sb.append("    limitYearAccumulated: ").append(toIndentedString(limitYearAccumulated))
            .append("\n");
        sb.append("    nonLimitYearAccumulated: ").append(toIndentedString(nonLimitYearAccumulated))
            .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
